### ISSUE TITLE
Getting GUID and other variables

### ISSUE THREAD

**Issue by Tomoli75** [rbowen/validate-echo-request-php#3]
I have no idea whatsoever on how to find these.

**Comment by Tutorialwork** [comment]
GUID is your SkillID without amzn1.ask.skill. you can find it in your skills overview. The userId can you find in the request from Amazon in context->System->user->userId.

**Comment by Tomoli75** [comment]
Thanks, but that was a bit late.
I posted on the 23rd of December 2018. It's the 4th of August, 2019!
:)
